# Generated by Django 5.0.6 on 2024-07-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='read_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
